# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-04-02 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('body', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='体温')),
                ('location', models.CharField(max_length=100, verbose_name='地理位置')),
                ('time', models.DateField(verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '健康报备',
                'verbose_name_plural': '健康报备',
                'db_table': 'tb_health',
            },
        ),
    ]
